import jsPDF from "jspdf";
import type { Assessment, BusinessInput } from "./finance";
import { rankSchemes } from "./schemes";

const rs = (n: number) => "Rs. " + Math.round(n).toLocaleString("en-IN");

export function downloadStatement(input: BusinessInput, a: Assessment) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = 56;

  doc.setFillColor(51, 65, 85);
  doc.rect(0, 0, W, 88, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold").setFontSize(18);
  doc.text("Sthanik Vikas AI", M, 40);
  doc.setFont("helvetica", "normal").setFontSize(11);
  doc.text("Bank-Ready Financial Statement | Micro-Business Co-Pilot", M, 62);
  y = 120;

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold").setFontSize(13);
  doc.text("1. Entrepreneur & Business Profile", M, y);
  y += 8;
  doc.setDrawColor(203, 213, 225).line(M, y, W - M, y);
  y += 20;

  doc.setFont("helvetica", "normal").setFontSize(11);
  const rows: [string, string][] = [
    ["Name", input.name || "-"],
    ["Business type", input.businessType || "-"],
    ["Location", input.city || "-"],
    ["Category / social group", input.category || "-"],
    ["Working days per month", String(input.workingDays)],
    ["Statement date", new Date().toLocaleDateString("en-IN")],
  ];
  for (const [k, v] of rows) {
    doc.setTextColor(100, 116, 139).text(k, M, y);
    doc.setTextColor(15, 23, 42).text(v, M + 200, y);
    y += 18;
  }

  y += 14;
  doc.setFont("helvetica", "bold").setFontSize(13).setTextColor(15, 23, 42);
  doc.text("2. Micro-Ledger Summary", M, y);
  y += 8;
  doc.line(M, y, W - M, y);
  y += 20;
  doc.setFont("helvetica", "normal").setFontSize(11);
  const ledger: [string, string][] = [
    ["Average daily income", rs(input.dailyIncome)],
    ["Average daily expense", rs(input.dailyExpense)],
    ["Estimated monthly income", rs(a.monthlyIncome)],
    ["Estimated monthly expense", rs(a.monthlyExpense)],
    ["Net monthly income", rs(a.net)],
    ["Profit margin", a.margin.toFixed(1) + " %"],
    ["Estimated annual turnover", rs(a.monthlyIncome * 12)],
    ["Business health", a.health.toUpperCase()],
  ];
  for (const [k, v] of ledger) {
    doc.setTextColor(100, 116, 139).text(k, M, y);
    doc.setTextColor(15, 23, 42).text(v, M + 200, y);
    y += 18;
  }

  y += 14;
  doc.setFont("helvetica", "bold").setFontSize(13);
  doc.text("3. Micro-Credit Assessment", M, y);
  y += 8;
  doc.line(M, y, W - M, y);
  y += 20;
  doc.setFont("helvetica", "normal").setFontSize(11);
  const credit: [string, string][] = [
    ["Eligibility score", a.score + " / 100"],
    ["Suggested loan ticket", rs(a.suggestedLoan)],
    ["Indicative affordable EMI (24 months)", rs(a.net * 0.35)],
  ];
  for (const [k, v] of credit) {
    doc.setTextColor(100, 116, 139).text(k, M, y);
    doc.setTextColor(15, 23, 42).text(v, M + 200, y);
    y += 18;
  }

  y += 14;
  doc.setFont("helvetica", "bold").setFontSize(13);
  doc.text("4. Recommended Government Schemes", M, y);
  y += 8;
  doc.line(M, y, W - M, y);
  y += 20;

  for (const { scheme, score } of rankSchemes(input, a).slice(0, 4)) {
    if (y > 720) {
      doc.addPage();
      y = 60;
    }
    doc.setFont("helvetica", "bold").setFontSize(11).setTextColor(15, 23, 42);
    doc.text(`${scheme.name}  (match ${score}%)`, M, y);
    y += 15;
    doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(71, 85, 105);
    for (const line of [
      `Loan limit: ${scheme.loanLimit}`,
      `Subsidy: ${scheme.subsidy}`,
      `Key benefit: ${scheme.benefits[0]}`,
    ]) {
      for (const l of doc.splitTextToSize(line, W - M * 2)) {
        doc.text(l, M, y);
        y += 13;
      }
    }
    y += 8;
  }

  if (y > 690) {
    doc.addPage();
    y = 60;
  }
  doc.setFontSize(9).setTextColor(148, 163, 184);
  for (const l of doc.splitTextToSize(
    "Disclaimer: This statement is a self-declared estimate generated by Sthanik Vikas AI from figures provided by the entrepreneur. It is intended to support a loan conversation and is not audited. Scheme details are indicative; confirm current terms with the lending bank or the concerned government portal.",
    W - M * 2,
  )) {
    doc.text(l, M, y);
    y += 12;
  }

  const safe = (input.name || "entrepreneur").replace(/[^A-Za-z0-9]+/g, "-").toLowerCase();
  doc.save(`financial-statement-${safe}.pdf`);
}
